import './globals.css';
import GlobalLayout from '@/components/layout/GlobalLayout';
import GlobalHeader from '@/components/layout/GlobalHeader';
import GlobalContent from '@/components/layout/GlobalContent';
import GlobalFooter from '@/components/layout/GlobalFooter';
import { cookies } from 'next/headers';

export const metadata = {
  title: 'ExpediPlan',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies();
  const themeColor = cookieStore.get('semi-color-scheme')?.value === 'dark' ? 'dark' : 'light';

  return (
    <html lang='en'>
      <body theme-mode={themeColor}>
        <GlobalLayout>
          <GlobalHeader />
          <GlobalContent>{children}</GlobalContent>
          <GlobalFooter />
        </GlobalLayout>
      </body>
    </html>
  );
}
